const CartActionTypes = {
    TOGGLE_CART_VISIBILITY: 'TOGGLE_CART_VISIBILITY',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM_FROM_CART:'REMOVE_ITEM_FROM_CART',
    CLEAR_CART:'CLEAR_CART'
  };
  
  export default CartActionTypes;